# This is a basic workflow to help you get started with Actions

name: Git_hub_actions_main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_tests:
    runs-on: ubuntu-latest
    
    steps:
     - name: RunTests
       run : cd .. ./test_mainscript.py
      
  
   
