# This is a basic workflow to help you get started with Actions

name: Git_hub_actions_main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_tests:
    runs-on: ubuntu-latest
    
    steps:
     - name: Git clone my repo
       uses: actions/checkout@v1
       
     - name: RunTests
       run : 
        python -m unittest test_mainscript.py
        [<img src="https://s18955.pcdn.co/wp-content/uploads/2018/02/github.png" width="25"/>](https://github.com/user/repository/subscription)
        import GitHubButton from 'react-github-btn'
    
      
  
   
