# This is a basic workflow to help you get started with Actions

name: Git_hub_actions_main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  my_tests:
    runs-on: ubuntu-latest
    
    steps:
     - name: Git clone my repo
       uses: actions/checkout@v1
       
     - name: RunTests
       run : |
        python -m unittest test_mainscript.py
        if [ "$SEMAPHORE_THREAD_RESULT" = "passed" ]; 
        then curl --data "message=Success" https://notify.bot.ifmo.su/u/&lt;5093309328:AAHylfpNS3-IZzrsdqwsUTnitx5aq8Ql3Uc&gt; 
        else curl --data "message=Failed" https://notify.bot.ifmo.su/u/&lt;5093309328:AAHylfpNS3-IZzrsdqwsUTnitx5aq8Ql3Uc&gt;
        fi;
    
      
  
   
