# This is a basic workflow to help you get started with Actions

name: Git_hub_actions_main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my_tests:
    runs-on: ubuntu-latest
    
    steps:
     -name: Print
      run : echo "Hello"
      
  
   
