# This is a basic workflow to help you get started with Actions

name: Git_hub_actions_main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_tests:
    runs-on: ubuntu-latest
    
    steps:
     - name: Git clone my repo
       uses: action/checkout@v1
       
     - name: RunTests
       run : |
        cd .. 
        cd ..
        cd ..
        pwd
        ./test_mainscript.py
    
    
      
  
   
